name: Build and Push

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 9
          run_install: false

      - uses: actions/setup-node@v4
        name: Install Node.js
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - uses: actions/cache@v4
        name: Build Cache
        with:
          path: |
            ${{ github.workspace }}/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/pnpm-lock.yaml') }}-${{ hashFiles('**/*.js', '**/*.jsx', '**/*.ts', '**/*.tsx') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/pnpm-lock.yaml') }}-

      - name: Build website
        env:
          BEI_AN_MODE: 'true'
        run: pnpm build

      - name: Initialize and Push to Build Branch
        run: |
          cd dist
          git init
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Actions"
          git add .
          git commit -m "Update build artifacts"
          git branch -M build
          git remote add origin https://github.com/${{ github.repository }}.git
          git push --force origin build
